# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_bfs')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_bfs')
    _bfs = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bfs', [dirname(__file__)])
        except ImportError:
            import _bfs
            return _bfs
        try:
            _mod = imp.load_module('_bfs', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _bfs = swig_import_helper()
    del swig_import_helper
else:
    import _bfs
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Vertex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vertex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vertex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vertex_id"] = _bfs.Vertex_vertex_id_set
    __swig_getmethods__["vertex_id"] = _bfs.Vertex_vertex_id_get
    if _newclass:
        vertex_id = _swig_property(_bfs.Vertex_vertex_id_get, _bfs.Vertex_vertex_id_set)
    __swig_setmethods__["prev_vertex_ids"] = _bfs.Vertex_prev_vertex_ids_set
    __swig_getmethods__["prev_vertex_ids"] = _bfs.Vertex_prev_vertex_ids_get
    if _newclass:
        prev_vertex_ids = _swig_property(_bfs.Vertex_prev_vertex_ids_get, _bfs.Vertex_prev_vertex_ids_set)
    __swig_setmethods__["is_visited"] = _bfs.Vertex_is_visited_set
    __swig_getmethods__["is_visited"] = _bfs.Vertex_is_visited_get
    if _newclass:
        is_visited = _swig_property(_bfs.Vertex_is_visited_get, _bfs.Vertex_is_visited_set)
    __swig_setmethods__["min_path_length"] = _bfs.Vertex_min_path_length_set
    __swig_getmethods__["min_path_length"] = _bfs.Vertex_min_path_length_get
    if _newclass:
        min_path_length = _swig_property(_bfs.Vertex_min_path_length_get, _bfs.Vertex_min_path_length_set)

    def __init__(self):
        this = _bfs.new_Vertex()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _bfs.delete_Vertex
    __del__ = lambda self: None
Vertex_swigregister = _bfs.Vertex_swigregister
Vertex_swigregister(Vertex)


def bfs(maxelements, k, m, d1, margin, nt):
    return _bfs.bfs(maxelements, k, m, d1, margin, nt)
bfs = _bfs.bfs

def bfs_visited_ids(maxelements, m, d1, nq, nt):
    return _bfs.bfs_visited_ids(maxelements, m, d1, nq, nt)
bfs_visited_ids = _bfs.bfs_visited_ids
# This file is compatible with both classic and new-style classes.


